<a href="https://colab.research.google.com/github/codestates/ds-sc13x/blob/master/sc13x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SC13x Linear Algebra

## 1. $\vec{c} \cdot \vec{d}$ 를 구해보세요. 이 두 개의 vector는 orthogonal 관계 (직교)에 있나요? 왜 그런가요? 왜 아닌가요?

\begin{align}
\vec{c} = \begin{bmatrix}3 & 7 & -2 & 12\end{bmatrix}
\qquad
\vec{d} = \begin{bmatrix}9 & -7 & 4 & 6\end{bmatrix}
\end{align}

In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
c = np.array([3, 7, -2, 12])
d = np.array([9, -7, 4, 6])

In [2]:
np.dot(c, d)

42

In [3]:
#내적이 0인 두 벡터로 구성된 행렬을 직교행렬이라 한다. 두 벡터의 내적은 0이아니기에 orthogonal 관계라 할 수 없다.

---

## 2. $E^{-1}$ 와 $E^{T}$ 를 구하세요.

\begin{align}
E = 
\begin{bmatrix}
    7 & 4 & 2 \\
    1 & 3 & -1 \\
    2 & 6 & -4
\end{bmatrix}
\end{align}

In [7]:
E = np.array([[7,4,2],[1,3,-1],[2,6,-4]])
E

array([[ 7,  4,  2],
       [ 1,  3, -1],
       [ 2,  6, -4]])

In [8]:
# E-1
np.linalg.inv(E)

array([[ 0.17647059, -0.82352941,  0.29411765],
       [-0.05882353,  0.94117647, -0.26470588],
       [ 0.        ,  1.        , -0.5       ]])

In [9]:
E.T

array([[ 7,  1,  2],
       [ 4,  3,  6],
       [ 2, -1, -4]])

---

## 3. $|F|$ 를 구하세요. 이 데이터는 어떤 의미가 있나요?

\begin{align}
F = 
\begin{bmatrix}
    2 & -2 & 5 \\
    4 & 1 & 10 \\
    12 & 6 & 30
\end{bmatrix}
\end{align}

In [12]:
# 벡터의 크기를 의미합니다.

In [20]:
F = np.array([[2,-2,5],[4,1,10],[12,6,30]])
F

array([[ 2, -2,  5],
       [ 4,  1, 10],
       [12,  6, 30]])

In [21]:
math.sqrt(sum(sum(F**2)))

35.07135583350036

---

## 4. 다음 데이터의 covariance, correlation을 구하세요.

- x = [820, 760, 1250, 990, 1080, 1450, 1600]

- y = [0, 1, 7, 1, 0, 6, 4]

In [22]:
x = np.array([820, 760, 1250, 990, 1080, 1450, 1600])
y = np.array([0, 1, 7, 1, 0, 6, 4])

In [24]:
cov = np.cov(x,y)
cov

array([[9.87619048e+04, 6.70238095e+02],
       [6.70238095e+02, 8.57142857e+00]])

In [25]:
cov[0,1]

670.2380952380952

In [26]:
x= np.std(x, ddof=1)
y= np.std(y, ddof=1)
corr = cov[0,1]/(x*y)
corr

0.7284634644730712

---

## 5. 다음 데이터를 정규화 하세요.

아래 링크를 참조하세요.

<https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html>

In [27]:
import pandas as pd

data = {"Country": ["England","Wales","Scotland","North Ireland"], 
        "Cheese": [105,103,103,66], 
        "Carcass_Meat": [245,227,242,267], 
        "Other_Meat": [685, 803, 750, 586], 
        "Fish": [147, 160, 122, 93], 
        "Fats_and_Oils": [193, 235, 184, 209], 
        "Sugars": [156, 175, 147, 139], 
        "Fresh_Potatoes": [720, 874, 566, 1033], 
        "Fresh_Veg": [253, 265, 171, 143], 
        "Other_Veg": [488, 570, 418, 355], 
        "Processed_Potatoes": [198, 203, 220, 187], 
        "Processed_Veg": [360, 365, 337, 334], 
        "Fresh_Fruit": [1102, 1137, 957, 674], 
        "Cereals": [1472, 1582, 1462, 1494], 
        "Beverages": [57,73,53,47], 
        "Soft_Drinks": [1374, 1256, 1572, 1506], 
        "Alcoholic Drinks": [375, 475, 458, 135], 
        "Confectionery": [54, 64, 62, 41]}

df = pd.DataFrame(data)

df

,Country,Cheese,Carcass_Meat,Other_Meat,Fish,Fats_and_Oils,Sugars,Fresh_Potatoes,Fresh_Veg,Other_Veg,Processed_Potatoes,Processed_Veg,Fresh_Fruit,Cereals,Beverages,Soft_Drinks,Alcoholic Drinks,Confectionery
0,England,105,245,685,147,193,156,720,253,488,198,360,1102,1472,57,1374,375,54
1,Wales,103,227,803,160,235,175,874,265,570,203,365,1137,1582,73,1256,475,64
2,Scotland,103,242,750,122,184,147,566,171,418,220,337,957,1462,53,1572,458,62
3,North Ireland,66,267,586,93,209,139,1033,143,355,187,334,674,1494,47,1506,135,41

In [31]:
df1 = df.set_index('Country')

In [32]:
from sklearn.preprocessing import StandardScaler

In [34]:
df_1 = StandardScaler().fit_transform(df1)
df_1

array([[ 0.65827466, -0.01749546, -0.25954622,  0.64458535, -0.63242919,
         0.13055067, -0.45007561,  0.86331183,  0.37773603, -0.33626508,
         0.80547723,  0.73740709, -0.64432226, -0.05191741, -0.43523112,
         0.10499766, -0.13830319],
       [ 0.53580495, -1.27716878,  1.19885635,  1.15244047,  1.53589947,
         1.54795798,  0.43569619,  1.09352832,  1.40168163,  0.08406627,
         1.17160324,  0.9292974 ,  1.67946294,  1.60943981, -1.40423624,
         0.84182336,  0.96812236],
       [ 0.53580495, -0.22744102,  0.54381113, -0.33205912, -1.09707105,
        -0.54085279, -1.33584741, -0.70983418, -0.49636387,  1.51319287,
        -0.87870243, -0.0575671 , -0.85557546, -0.46725672,  1.19072664,
         0.71656299,  0.74683725],
       [-1.72988456,  1.52210526, -1.48312126, -1.4649667 ,  0.19360077,
        -1.13765587,  1.35022682, -1.24700598, -1.28305378, -1.26099406,
        -1.09837804, -1.60913739, -0.17956522, -1.09026568,  0.64874072,
        -1.66338402, -1.57665641]])

## 6. 위 데이터에 PCA 를 적용 후 scatterplot을 그리세요.

In [35]:
df_1.shape

(4, 17)

In [56]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
af_pca = pca.fit(df_1)
af_pca

PCA(n_components=2)

In [57]:
print(pca.components_)
print(pca.explained_variance_)

[[-0.24572131  0.28562914 -0.26481055 -0.28611787 -0.12719487 -0.2811012
   0.09775901 -0.26544997 -0.28708628 -0.12073819 -0.25767815 -0.27890521
  -0.17843996 -0.27747513  0.22771961 -0.25509484 -0.25275834]
 [ 0.24708041 -0.07716993  0.13610704 -0.01100602 -0.40054501 -0.13684092
  -0.45468785 -0.0964863  -0.09282322  0.41036129 -0.1539603   0.08174644
  -0.32902948 -0.13773847  0.29323981  0.23231808  0.21105701]]
[15.48765084  5.63749203]

In [59]:
DF = pca.transform(df_1)
DF

array([[-0.95448984,  0.32831832],
       [-4.52095094, -1.73537967],
       [ 0.48797835,  3.23367195],
       [ 4.98746242, -1.8266106 ]])

In [60]:
DF = pd.DataFrame(data=DF, columns = ['PC1', 'PC2'])
DF

        PC1       PC2
0 -0.954490  0.328318
1 -4.520951 -1.735380
2  0.487978  3.233672
3  4.987462 -1.826611

In [62]:
DF = pd.concat([DF, df['Country']], axis=1)
DF

        PC1       PC2        Country
0 -0.954490  0.328318        England
1 -4.520951 -1.735380          Wales
2  0.487978  3.233672       Scotland
3  4.987462 -1.826611  North Ireland

In [68]:
import seaborn as sns
sns.scatterplot(data=DF, x='PC1', y='PC2', hue='Country')

ModuleNotFoundError: No module named 'seaborn'

In [67]:
!conda install seaborn

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/gun/opt/anaconda3

  added / updated specs:
    - seaborn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py37hecd8cb5_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                        4.8.2-py37_0 --> 4.9.2-py37hecd8cb5_0


Proceed ([y]/n)? ^C

CondaSystemExit:
Operation aborted.  Exiting.

## 7. 아래 데이터에 대해 k-means clustering을 적용 후, 결과를 그래프로 그리세요.

In [ ]:
points = pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/sc13x/data.csv')
points.head()

          x         y
0 -7.846803 -3.421277
1 -3.554323 -6.884729
2 -0.192822 -9.671030
3 -6.401456 -5.223972
4 -0.804026 -9.704457

In [ ]:
points.shape

(200, 2)

In [ ]:
# 이 곳에 답안을 작성하시기 바랍니다.

# SC 3점 요구사항:
위에서 요구된 사항들을 모두 정확하게 만족하였으며, 아직 시간이 남았다면 아래 2개의 추가 조건들 중 하나를 만족하는 경우 3점을 얻을 수 있습니다.

아래 요구사항들은 모두 **optional** 임을 다시 한 번 강조합니다. (필수 요구사항이 아닙니다.)

- 6번의 PCA 결과에 대해서 `Scree plot`을 추가하세요.

- 7번에서 k값을 선택하는 과정을 논리적으로 설명하세요.

In [ ]:
# 이 곳에 답안을 작성하시기 바랍니다.